### ISSUE TITLE
Create a proper README and requirements.txt file 

### ISSUE THREAD

**Issue by giliam** [tum-ens/pyPRIMA#20]
Hi!

It would be nice to have a **start from scratch** README file.
I have already identified the necessary python packages:

- geopandas
- geopy
- numpy
- gdal
- pandas
- pysal
- scipy
- pyshp
- shapely

I can run the script but I miss all input data (shapefiles, rasters, csv, etc.). Do you have any clue how I could get a minimal working code on the time load series?

**Comment by kais-siala** [comment]
Hi! Sorry, I just read your issue. I am working on that. The documentation should be done by end of November. It will include the sources that I recommend, and how to download the data from there.
